name: compile

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  compile:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Set up and Compile MQL5
        uses: fx31337/mql-compile-action@v2
        with:
          path: ExpertAdvisor.mq5
          init-platform: true
          mt-version: 5.0.0.4500
          verbose: true
